services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - kroki

  kroki:
    image: yuzutech/kroki
    depends_on:
      - mermaid
      - bpmn
      - excalidraw
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8000:8000"
    tmpfs:
      - /tmp:exec

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"

  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"

  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"